def manejo_errores(exception):
    print(f"Error {exception}")
    